# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

variables:
- name: azureSubscriptionEndpoint
  value: CNB
- name: azureContainerRegistry
  value: eshopcnb.azurecr.io
  
steps:
    
- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: eshop
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
    includeLatestTag: true
    
- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: eshop
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
    includeLatestTag: true
